### ISSUE TITLE
Seems broken when nesting deeper than two levels

### ISSUE THREAD

**Issue by m1keil** [aprilandjan/vscode-ascii-tree-generator#13]
Input:

```
root
  branch
    item
    item
```

Got:
```
.
└── root
    └── branch
        └── item
            └── item
```

Expected:
```
.
└── root
    └── branch
        ├── item
        └── item
```

**Comment by aprilandjan** [comment]
@m1keil hi, Thanks for your feedback! Yeah it seems that the formatter for `indent` characters seems buggy, I'll check into this.

Besides, you can use `#` to mark depth instead, it works as expected:

```
# root
## branch
### item
### item
```

**Comment by aprilandjan** [comment]
Remove the introduction (temporarily) for indent character usage in Readme since it is buggy and not practical 🤔
